# Generated by Django 4.2.7 on 2023-11-02 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studdb',
            old_name='finshing_date',
            new_name='finishing_date',
        ),
    ]
